/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.f16.ftech.dao;

import java.util.Date;
import com.f16.ftech.dto.*;
import com.f16.ftech.exceptions.*;

public interface ClientesFtechDao
{
	/** 
	 * Inserts a new row in the CLIENTES_FTECH table.
	 */
	public ClientesFtechPk insert(ClientesFtech dto) throws ClientesFtechDaoException;

	/** 
	 * Updates a single row in the CLIENTES_FTECH table.
	 */
	public void update(ClientesFtechPk pk, ClientesFtech dto) throws ClientesFtechDaoException;

	/** 
	 * Deletes a single row in the CLIENTES_FTECH table.
	 */
	public void delete(ClientesFtechPk pk) throws ClientesFtechDaoException;

	/** 
	 * Returns the rows from the CLIENTES_FTECH table that matches the specified primary-key value.
	 */
	public ClientesFtech findByPrimaryKey(ClientesFtechPk pk) throws ClientesFtechDaoException;

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'ID_CLIENTE = :idCliente'.
	 */
	public ClientesFtech findByPrimaryKey(int idCliente) throws ClientesFtechDaoException;

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria ''.
	 */
	public ClientesFtech[] findAll() throws ClientesFtechDaoException;

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'ID_CLIENTE = :idCliente'.
	 */
	public ClientesFtech[] findWhereIdClienteEquals(int idCliente) throws ClientesFtechDaoException;

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'NUMERO_CC = :numeroCc'.
	 */
	public ClientesFtech[] findWhereNumeroCcEquals(int numeroCc) throws ClientesFtechDaoException;

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'NOME = :nome'.
	 */
	public ClientesFtech[] findWhereNomeEquals(String nome) throws ClientesFtechDaoException;

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'MORADA = :morada'.
	 */
	public ClientesFtech[] findWhereMoradaEquals(String morada) throws ClientesFtechDaoException;

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'DATA_NASCIMENTO = :dataNascimento'.
	 */
	public ClientesFtech[] findWhereDataNascimentoEquals(Date dataNascimento) throws ClientesFtechDaoException;

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'DATA_INSERCAO = :dataInsercao'.
	 */
	public ClientesFtech[] findWhereDataInsercaoEquals(Date dataInsercao) throws ClientesFtechDaoException;

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'GENERO = :genero'.
	 */
	public ClientesFtech[] findWhereGeneroEquals(String genero) throws ClientesFtechDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the specified arbitrary SQL statement
	 */
	public ClientesFtech[] findByDynamicSelect(String sql, Object[] sqlParams) throws ClientesFtechDaoException;

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the specified arbitrary SQL statement
	 */
	public ClientesFtech[] findByDynamicWhere(String sql, Object[] sqlParams) throws ClientesFtechDaoException;

}
