/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.f16.ftech.jdbc;

import com.f16.ftech.dao.*;
import com.f16.ftech.factory.*;
import java.util.Date;
import com.f16.ftech.dto.*;
import com.f16.ftech.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ClientesFtechDaoImpl extends AbstractDAO implements ClientesFtechDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_CLIENTE, NUMERO_CC, NOME, MORADA, DATA_NASCIMENTO, DATA_INSERCAO, GENERO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_CLIENTE, NUMERO_CC, NOME, MORADA, DATA_NASCIMENTO, DATA_INSERCAO, GENERO ) VALUES ( ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_CLIENTE = ?, NUMERO_CC = ?, NOME = ?, MORADA = ?, DATA_NASCIMENTO = ?, DATA_INSERCAO = ?, GENERO = ? WHERE ID_CLIENTE = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_CLIENTE = ?";

	/** 
	 * Index of column ID_CLIENTE
	 */
	protected static final int COLUMN_ID_CLIENTE = 1;

	/** 
	 * Index of column NUMERO_CC
	 */
	protected static final int COLUMN_NUMERO_CC = 2;

	/** 
	 * Index of column NOME
	 */
	protected static final int COLUMN_NOME = 3;

	/** 
	 * Index of column MORADA
	 */
	protected static final int COLUMN_MORADA = 4;

	/** 
	 * Index of column DATA_NASCIMENTO
	 */
	protected static final int COLUMN_DATA_NASCIMENTO = 5;

	/** 
	 * Index of column DATA_INSERCAO
	 */
	protected static final int COLUMN_DATA_INSERCAO = 6;

	/** 
	 * Index of column GENERO
	 */
	protected static final int COLUMN_GENERO = 7;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 7;

	/** 
	 * Index of primary-key column ID_CLIENTE
	 */
	protected static final int PK_COLUMN_ID_CLIENTE = 1;

	/** 
	 * Inserts a new row in the CLIENTES_FTECH table.
	 */
	public ClientesFtechPk insert(ClientesFtech dto) throws ClientesFtechDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getIdCliente() );
			stmt.setInt( index++, dto.getNumeroCc() );
			stmt.setString( index++, dto.getNome() );
			stmt.setString( index++, dto.getMorada() );
			stmt.setTimestamp(index++, dto.getDataNascimento()==null ? null : new java.sql.Timestamp( dto.getDataNascimento().getTime() ) );
			stmt.setTimestamp(index++, dto.getDataInsercao()==null ? null : new java.sql.Timestamp( dto.getDataInsercao().getTime() ) );
			stmt.setString( index++, dto.getGenero() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ClientesFtechDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the CLIENTES_FTECH table.
	 */
	public void update(ClientesFtechPk pk, ClientesFtech dto) throws ClientesFtechDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdCliente() );
			stmt.setInt( index++, dto.getNumeroCc() );
			stmt.setString( index++, dto.getNome() );
			stmt.setString( index++, dto.getMorada() );
			stmt.setTimestamp(index++, dto.getDataNascimento()==null ? null : new java.sql.Timestamp( dto.getDataNascimento().getTime() ) );
			stmt.setTimestamp(index++, dto.getDataInsercao()==null ? null : new java.sql.Timestamp( dto.getDataInsercao().getTime() ) );
			stmt.setString( index++, dto.getGenero() );
			stmt.setInt( 8, pk.getIdCliente() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ClientesFtechDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the CLIENTES_FTECH table.
	 */
	public void delete(ClientesFtechPk pk) throws ClientesFtechDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdCliente() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ClientesFtechDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the CLIENTES_FTECH table that matches the specified primary-key value.
	 */
	public ClientesFtech findByPrimaryKey(ClientesFtechPk pk) throws ClientesFtechDaoException
	{
		return findByPrimaryKey( pk.getIdCliente() );
	}

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'ID_CLIENTE = :idCliente'.
	 */
	public ClientesFtech findByPrimaryKey(int idCliente) throws ClientesFtechDaoException
	{
		ClientesFtech ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_CLIENTE = ?", new Object[] {  new Integer(idCliente) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria ''.
	 */
	public ClientesFtech[] findAll() throws ClientesFtechDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_CLIENTE", null );
	}

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'ID_CLIENTE = :idCliente'.
	 */
	public ClientesFtech[] findWhereIdClienteEquals(int idCliente) throws ClientesFtechDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_CLIENTE = ? ORDER BY ID_CLIENTE", new Object[] {  new Integer(idCliente) } );
	}

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'NUMERO_CC = :numeroCc'.
	 */
	public ClientesFtech[] findWhereNumeroCcEquals(int numeroCc) throws ClientesFtechDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NUMERO_CC = ? ORDER BY NUMERO_CC", new Object[] {  new Integer(numeroCc) } );
	}

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'NOME = :nome'.
	 */
	public ClientesFtech[] findWhereNomeEquals(String nome) throws ClientesFtechDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NOME = ? ORDER BY NOME", new Object[] { nome } );
	}

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'MORADA = :morada'.
	 */
	public ClientesFtech[] findWhereMoradaEquals(String morada) throws ClientesFtechDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE MORADA = ? ORDER BY MORADA", new Object[] { morada } );
	}

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'DATA_NASCIMENTO = :dataNascimento'.
	 */
	public ClientesFtech[] findWhereDataNascimentoEquals(Date dataNascimento) throws ClientesFtechDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DATA_NASCIMENTO = ? ORDER BY DATA_NASCIMENTO", new Object[] { dataNascimento==null ? null : new java.sql.Timestamp( dataNascimento.getTime() ) } );
	}

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'DATA_INSERCAO = :dataInsercao'.
	 */
	public ClientesFtech[] findWhereDataInsercaoEquals(Date dataInsercao) throws ClientesFtechDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE DATA_INSERCAO = ? ORDER BY DATA_INSERCAO", new Object[] { dataInsercao==null ? null : new java.sql.Timestamp( dataInsercao.getTime() ) } );
	}

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the criteria 'GENERO = :genero'.
	 */
	public ClientesFtech[] findWhereGeneroEquals(String genero) throws ClientesFtechDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE GENERO = ? ORDER BY GENERO", new Object[] { genero } );
	}

	/**
	 * Method 'ClientesFtechDaoImpl'
	 * 
	 */
	public ClientesFtechDaoImpl()
	{
	}

	/**
	 * Method 'ClientesFtechDaoImpl'
	 * 
	 * @param userConn
	 */
	public ClientesFtechDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "U3245.CLIENTES_FTECH";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected ClientesFtech fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			ClientesFtech dto = new ClientesFtech();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected ClientesFtech[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			ClientesFtech dto = new ClientesFtech();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		ClientesFtech ret[] = new ClientesFtech[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(ClientesFtech dto, ResultSet rs) throws SQLException
	{
		dto.setIdCliente( rs.getInt( COLUMN_ID_CLIENTE ) );
		dto.setNumeroCc( rs.getInt( COLUMN_NUMERO_CC ) );
		dto.setNome( rs.getString( COLUMN_NOME ) );
		dto.setMorada( rs.getString( COLUMN_MORADA ) );
		dto.setDataNascimento( rs.getTimestamp(COLUMN_DATA_NASCIMENTO ) );
		dto.setDataInsercao( rs.getTimestamp(COLUMN_DATA_INSERCAO ) );
		dto.setGenero( rs.getString( COLUMN_GENERO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(ClientesFtech dto)
	{
	}

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the specified arbitrary SQL statement
	 */
	public ClientesFtech[] findByDynamicSelect(String sql, Object[] sqlParams) throws ClientesFtechDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ClientesFtechDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the CLIENTES_FTECH table that match the specified arbitrary SQL statement
	 */
	public ClientesFtech[] findByDynamicWhere(String sql, Object[] sqlParams) throws ClientesFtechDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ClientesFtechDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
