/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.f16.ftech.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.f16.ftech.dao.ClientesFtechDao;
import com.f16.ftech.dto.ClientesFtech;
import com.f16.ftech.exceptions.ClientesFtechDaoException;
import com.f16.ftech.factory.ClientesFtechDaoFactory;

public class ClientesFtechDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdClienteEquals(0);
		// findWhereNumeroCcEquals(0);
		// findWhereNomeEquals("");
		// findWhereMoradaEquals("");
		// findWhereDataNascimentoEquals(null);
		// findWhereDataInsercaoEquals(null);
		// findWhereGeneroEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ClientesFtechDao _dao = getClientesFtechDao();
			ClientesFtech _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdClienteEquals'
	 * 
	 * @param idCliente
	 */
	public static void findWhereIdClienteEquals(int idCliente)
	{
		try {
			ClientesFtechDao _dao = getClientesFtechDao();
			ClientesFtech _result[] = _dao.findWhereIdClienteEquals(idCliente);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNumeroCcEquals'
	 * 
	 * @param numeroCc
	 */
	public static void findWhereNumeroCcEquals(int numeroCc)
	{
		try {
			ClientesFtechDao _dao = getClientesFtechDao();
			ClientesFtech _result[] = _dao.findWhereNumeroCcEquals(numeroCc);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNomeEquals'
	 * 
	 * @param nome
	 */
	public static void findWhereNomeEquals(String nome)
	{
		try {
			ClientesFtechDao _dao = getClientesFtechDao();
			ClientesFtech _result[] = _dao.findWhereNomeEquals(nome);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereMoradaEquals'
	 * 
	 * @param morada
	 */
	public static void findWhereMoradaEquals(String morada)
	{
		try {
			ClientesFtechDao _dao = getClientesFtechDao();
			ClientesFtech _result[] = _dao.findWhereMoradaEquals(morada);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDataNascimentoEquals'
	 * 
	 * @param dataNascimento
	 */
	public static void findWhereDataNascimentoEquals(Date dataNascimento)
	{
		try {
			ClientesFtechDao _dao = getClientesFtechDao();
			ClientesFtech _result[] = _dao.findWhereDataNascimentoEquals(dataNascimento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDataInsercaoEquals'
	 * 
	 * @param dataInsercao
	 */
	public static void findWhereDataInsercaoEquals(Date dataInsercao)
	{
		try {
			ClientesFtechDao _dao = getClientesFtechDao();
			ClientesFtech _result[] = _dao.findWhereDataInsercaoEquals(dataInsercao);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereGeneroEquals'
	 * 
	 * @param genero
	 */
	public static void findWhereGeneroEquals(String genero)
	{
		try {
			ClientesFtechDao _dao = getClientesFtechDao();
			ClientesFtech _result[] = _dao.findWhereGeneroEquals(genero);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getClientesFtechDao'
	 * 
	 * @return ClientesFtechDao
	 */
	public static ClientesFtechDao getClientesFtechDao()
	{
		return ClientesFtechDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(ClientesFtech dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdCliente() );
		buf.append( ", " );
		buf.append( dto.getNumeroCc() );
		buf.append( ", " );
		buf.append( dto.getNome() );
		buf.append( ", " );
		buf.append( dto.getMorada() );
		buf.append( ", " );
		buf.append( dto.getDataNascimento() );
		buf.append( ", " );
		buf.append( dto.getDataInsercao() );
		buf.append( ", " );
		buf.append( dto.getGenero() );
		System.out.println( buf.toString() );
	}

}
