/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.f16.ftech.j2ee.session;

import com.f16.ftech.factory.*;
import com.f16.ftech.dao.*;
import com.f16.ftech.dto.*;
import com.f16.ftech.exceptions.*;
import java.rmi.RemoteException;
import java.math.*;
import java.util.Date;
import javax.ejb.*;

public class ClientesFtechSessionBean implements SessionBean
{
	protected ClientesFtechDao daoImpl = createDao();

	/** 
	 * Inserts a new row in the CLIENTES_FTECH table.
	 */
	public ClientesFtechPk insert(ClientesFtech dto) throws ClientesFtechDaoException
	{
		try {
			return daoImpl.insert(dto);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Updates a single row in the CLIENTES_FTECH table.
	 */
	public void update(ClientesFtechPk pk, ClientesFtech dto) throws ClientesFtechDaoException
	{
		try {
			daoImpl.update(pk, dto);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Deletes a single row in the CLIENTES_FTECH table.
	 */
	public void delete(ClientesFtechPk pk) throws ClientesFtechDaoException
	{
		try {
			daoImpl.delete(pk);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Returns the rows from the CLIENTES_FTECH table that matches the specified primary-key value.
	 */
	public ClientesFtech findByPrimaryKey(ClientesFtechPk pk) throws ClientesFtechDaoException
	{
		return findByPrimaryKey( pk.getIdCliente() );
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param idCliente
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech
	 */
	public ClientesFtech findByPrimaryKey(int idCliente) throws ClientesFtechDaoException
	{
		try {
			return daoImpl.findByPrimaryKey(idCliente);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findAll'
	 * 
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findAll() throws ClientesFtechDaoException
	{
		try {
			return daoImpl.findAll();
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereIdClienteEquals'
	 * 
	 * @param idCliente
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereIdClienteEquals(int idCliente) throws ClientesFtechDaoException
	{
		try {
			return daoImpl.findWhereIdClienteEquals(idCliente);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereNumeroCcEquals'
	 * 
	 * @param numeroCc
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereNumeroCcEquals(int numeroCc) throws ClientesFtechDaoException
	{
		try {
			return daoImpl.findWhereNumeroCcEquals(numeroCc);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereNomeEquals'
	 * 
	 * @param nome
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereNomeEquals(String nome) throws ClientesFtechDaoException
	{
		try {
			return daoImpl.findWhereNomeEquals(nome);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereMoradaEquals'
	 * 
	 * @param morada
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereMoradaEquals(String morada) throws ClientesFtechDaoException
	{
		try {
			return daoImpl.findWhereMoradaEquals(morada);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereDataNascimentoEquals'
	 * 
	 * @param dataNascimento
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereDataNascimentoEquals(Date dataNascimento) throws ClientesFtechDaoException
	{
		try {
			return daoImpl.findWhereDataNascimentoEquals(dataNascimento);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereDataInsercaoEquals'
	 * 
	 * @param dataInsercao
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereDataInsercaoEquals(Date dataInsercao) throws ClientesFtechDaoException
	{
		try {
			return daoImpl.findWhereDataInsercaoEquals(dataInsercao);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereGeneroEquals'
	 * 
	 * @param genero
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereGeneroEquals(String genero) throws ClientesFtechDaoException
	{
		try {
			return daoImpl.findWhereGeneroEquals(genero);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param arg
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findByDynamicSelect(String sql, Object[] arg) throws ClientesFtechDaoException
	{
		try {
			return daoImpl.findByDynamicSelect(sql, arg);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param arg
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findByDynamicWhere(String sql, Object[] arg) throws ClientesFtechDaoException
	{
		try {
			return daoImpl.findByDynamicWhere(sql, arg);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'ejbActivate'
	 * 
	 */
	public void ejbActivate()
	{
	}

	/**
	 * Method 'ejbPassivate'
	 * 
	 */
	public void ejbPassivate()
	{
	}

	/**
	 * Method 'ejbCreate'
	 * 
	 */
	public void ejbCreate()
	{
	}

	/**
	 * Method 'ejbRemove'
	 * 
	 */
	public void ejbRemove()
	{
	}

	/**
	 * Method 'setSessionContext'
	 * 
	 * @param ctx
	 */
	public void setSessionContext(SessionContext ctx)
	{
	}

	/**
	 * Method 'unsetSessionContext'
	 * 
	 */
	public void unsetSessionContext()
	{
	}

	/**
	 * Method 'createDao'
	 * 
	 * @return ClientesFtechDao
	 */
	protected ClientesFtechDao createDao()
	{
		return ClientesFtechDaoFactory.create();
	}

}
