/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.f16.ftech.j2ee.session;

import com.f16.ftech.dto.*;
import com.f16.ftech.exceptions.*;
import java.rmi.RemoteException;
import java.util.Date;
import javax.ejb.*;

public interface ClientesFtechSession extends EJBObject
{
	/** 
	 * Inserts a new row in the CLIENTES_FTECH table.
	 */
	public ClientesFtechPk insert(ClientesFtech dto) throws ClientesFtechDaoException, RemoteException;

	/** 
	 * Updates a single row in the CLIENTES_FTECH table.
	 */
	public void update(ClientesFtechPk pk, ClientesFtech dto) throws ClientesFtechDaoException, RemoteException;

	/** 
	 * Deletes a single row in the CLIENTES_FTECH table.
	 */
	public void delete(ClientesFtechPk pk) throws ClientesFtechDaoException, RemoteException;

	/** 
	 * Returns the rows from the CLIENTES_FTECH table that matches the specified primary-key value.
	 */
	public ClientesFtech findByPrimaryKey(ClientesFtechPk pk) throws ClientesFtechDaoException, RemoteException;

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param idCliente
	 * @throws ClientesFtechDaoException
	 * @throws RemoteException
	 * @return ClientesFtech
	 */
	public ClientesFtech findByPrimaryKey(int idCliente) throws ClientesFtechDaoException, RemoteException;

	/**
	 * Method 'findAll'
	 * 
	 * @throws ClientesFtechDaoException
	 * @throws RemoteException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findAll() throws ClientesFtechDaoException, RemoteException;

	/**
	 * Method 'findWhereIdClienteEquals'
	 * 
	 * @param idCliente
	 * @throws ClientesFtechDaoException
	 * @throws RemoteException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereIdClienteEquals(int idCliente) throws ClientesFtechDaoException, RemoteException;

	/**
	 * Method 'findWhereNumeroCcEquals'
	 * 
	 * @param numeroCc
	 * @throws ClientesFtechDaoException
	 * @throws RemoteException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereNumeroCcEquals(int numeroCc) throws ClientesFtechDaoException, RemoteException;

	/**
	 * Method 'findWhereNomeEquals'
	 * 
	 * @param nome
	 * @throws ClientesFtechDaoException
	 * @throws RemoteException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereNomeEquals(String nome) throws ClientesFtechDaoException, RemoteException;

	/**
	 * Method 'findWhereMoradaEquals'
	 * 
	 * @param morada
	 * @throws ClientesFtechDaoException
	 * @throws RemoteException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereMoradaEquals(String morada) throws ClientesFtechDaoException, RemoteException;

	/**
	 * Method 'findWhereDataNascimentoEquals'
	 * 
	 * @param dataNascimento
	 * @throws ClientesFtechDaoException
	 * @throws RemoteException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereDataNascimentoEquals(Date dataNascimento) throws ClientesFtechDaoException, RemoteException;

	/**
	 * Method 'findWhereDataInsercaoEquals'
	 * 
	 * @param dataInsercao
	 * @throws ClientesFtechDaoException
	 * @throws RemoteException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereDataInsercaoEquals(Date dataInsercao) throws ClientesFtechDaoException, RemoteException;

	/**
	 * Method 'findWhereGeneroEquals'
	 * 
	 * @param genero
	 * @throws ClientesFtechDaoException
	 * @throws RemoteException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereGeneroEquals(String genero) throws ClientesFtechDaoException, RemoteException;

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param arg
	 * @throws ClientesFtechDaoException
	 * @throws RemoteException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findByDynamicSelect(String sql, Object[] arg) throws ClientesFtechDaoException, RemoteException;

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param arg
	 * @throws ClientesFtechDaoException
	 * @throws RemoteException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findByDynamicWhere(String sql, Object[] arg) throws ClientesFtechDaoException, RemoteException;

}
