/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.f16.ftech.j2ee.delegate;

import com.f16.ftech.dao.*;
import com.f16.ftech.dto.*;
import com.f16.ftech.exceptions.*;
import com.f16.ftech.j2ee.session.*;
import java.util.Date;

public class ClientesFtechDelegate implements ClientesFtechDao
{
	protected ClientesFtechSession session;

	protected int maxRows;

	/**
	 * Method 'ClientesFtechDelegate'
	 * 
	 * @param session
	 */
	public ClientesFtechDelegate(final ClientesFtechSession session)
	{
		this.session = session;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/** 
	 * Inserts a new row in the CLIENTES_FTECH table.
	 */
	public ClientesFtechPk insert(ClientesFtech dto) throws ClientesFtechDaoException
	{
		try {
			return session.insert(dto);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Updates a single row in the CLIENTES_FTECH table.
	 */
	public void update(ClientesFtechPk pk, ClientesFtech dto) throws ClientesFtechDaoException
	{
		try {
			session.update(pk, dto);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/** 
	 * Deletes a single row in the CLIENTES_FTECH table.
	 */
	public void delete(ClientesFtechPk pk) throws ClientesFtechDaoException
	{
		try {
			session.delete(pk);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param pk
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech
	 */
	public ClientesFtech findByPrimaryKey(ClientesFtechPk pk) throws ClientesFtechDaoException
	{
		try {
			return session.findByPrimaryKey(pk);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByPrimaryKey'
	 * 
	 * @param idCliente
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech
	 */
	public ClientesFtech findByPrimaryKey(int idCliente) throws ClientesFtechDaoException
	{
		try {
			return session.findByPrimaryKey(idCliente);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findAll'
	 * 
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findAll() throws ClientesFtechDaoException
	{
		try {
			return session.findAll();
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereIdClienteEquals'
	 * 
	 * @param idCliente
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereIdClienteEquals(int idCliente) throws ClientesFtechDaoException
	{
		try {
			return session.findWhereIdClienteEquals(idCliente);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereNumeroCcEquals'
	 * 
	 * @param numeroCc
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereNumeroCcEquals(int numeroCc) throws ClientesFtechDaoException
	{
		try {
			return session.findWhereNumeroCcEquals(numeroCc);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereNomeEquals'
	 * 
	 * @param nome
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereNomeEquals(String nome) throws ClientesFtechDaoException
	{
		try {
			return session.findWhereNomeEquals(nome);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereMoradaEquals'
	 * 
	 * @param morada
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereMoradaEquals(String morada) throws ClientesFtechDaoException
	{
		try {
			return session.findWhereMoradaEquals(morada);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereDataNascimentoEquals'
	 * 
	 * @param dataNascimento
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereDataNascimentoEquals(Date dataNascimento) throws ClientesFtechDaoException
	{
		try {
			return session.findWhereDataNascimentoEquals(dataNascimento);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereDataInsercaoEquals'
	 * 
	 * @param dataInsercao
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereDataInsercaoEquals(Date dataInsercao) throws ClientesFtechDaoException
	{
		try {
			return session.findWhereDataInsercaoEquals(dataInsercao);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findWhereGeneroEquals'
	 * 
	 * @param genero
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findWhereGeneroEquals(String genero) throws ClientesFtechDaoException
	{
		try {
			return session.findWhereGeneroEquals(genero);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicSelect'
	 * 
	 * @param sql
	 * @param sqlParams
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findByDynamicSelect(String sql, Object[] sqlParams) throws ClientesFtechDaoException
	{
		try {
			return session.findByDynamicSelect(sql, sqlParams);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

	/**
	 * Method 'findByDynamicWhere'
	 * 
	 * @param sql
	 * @param sqlParams
	 * @throws ClientesFtechDaoException
	 * @return ClientesFtech[]
	 */
	public ClientesFtech[] findByDynamicWhere(String sql, Object[] sqlParams) throws ClientesFtechDaoException
	{
		try {
			return session.findByDynamicWhere(sql, sqlParams);
		}
		catch (ClientesFtechDaoException daoException) {
			throw daoException;
		}
		catch (Exception ex) {
			ex.printStackTrace();
			throw new ClientesFtechDaoException( ex.getMessage() );
		}
		
	}

}
